---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Small-Scale Research Projects"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 
lastmod: 2021-11-09T11:17:19-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Practical Exercises as _Small-Scale Research Projects_ (SSRPs) on multi-scales and –processes modelling, observations, data visualization, analysis, and assessment for environmental applications led by teachers - [Risto Makkonen](/authors/makkonen/), [Michael Boy](/authors/boy/), [Alexander Mahura](/authors/mahura/), [Roman Nuterman](/authors/nuterman/) – whom designed and realized SSRPs with students. Info-Poster on Seamless Multi-Scale and –Processes Modelling → <a href="/media/InfoPoster_INAR_MultiScaleProcesModel.pdf" target="_blank" rel="noopener"><i class="fas fa-file-pdf"></i></a>

SSRPs are arranged from 2nd day until official oral presentation/ defense of research projects’ outcomes on the last day of the school.

*List of participants assigned to work in groups on small-scale research projects* <a href="/media/MEGAPOLIS-2021_Groups-by-models.pdf" target="_blank" rel="noopener"><i class="fas fa-file-pdf"></i></a>

## SSRP Groups

- **ARCA** - Resp. [Michael Boy](/authors/boy/), [Petri Clusius](/authors/petri/) <br>
The Atmospherically Relevant Chemistry and Aerosol Box Model (ARCA box) is used for simulating atmospheric chemistry and the time evolution of aerosol particles and the formation of stable molecular clusters. The backbone of ARCAs
chemical library comes from the Master Chemical Mechanism (MCM), extended with Peroxy Radical Autoxidation Mechanism (PRAM), and is further extendable with any new reactions. Molecular clustering is simulated with the
Atmospheric Cluster Dynamics Code (ACDC). The particle size distribution is represented with two alternative methods whose size and grid density are fully configurable. The evolution of the particle size distribution due to the
condensation of low volatile organic vapors and the Brownian coagulation is simulated using established kinetic and thermodynamic theories. ARCA also provides a graphical user interface which improves its usability and repeatability of
the simulations. A detailed manual and several tutorials are available at the MSM website under ‘ARCA box’. <br>
**See also:** <br>
  - https://www2.helsinki.fi/en/researchgroups/multi-scale-modelling/atmospherically-relevant-chemistry-and-aerosol-box-model

---

- **Enviro-HIRLAM** - Resp.  [Alexander Mahura](/authors/mahura/), [Roman Nuterman](/authors/nuterman/), [Georgii Nerobelov](/authors/nerobelov/), [Mykhailo Savenets](/authors/savenets/) <br>
Enviro-HIRLAM (see [Baklanov et al., 2017](https://doi.org/10.5194/gmd-10-2971-2017
)) is a fully online-coupled ACT-NWP (Atmospheric Chemistry Transport – Numerical Weather Prediction) modeling system for regional-, meso- and urban scale different environmental applications. The NWP part
developed by HIRLAM consortium is used for operational weather forecasting. The Enviro-components were mainly developed in a close collaboration with the Universities from different countries. It includes of gas-phase chemistry CBMZ
and aerosol microphysics M7 which includes sulfate, mineral dust, sea-salt, black and organic carbon. There are modules of urbanization for land surface scheme, natural and anthropogenic emissions, nucleation, coagulation,
condensation, dry and wet deposition, and sedimentation of aerosols. The Savijarvi radiation scheme has been improved to account explicitly for aerosol radiation interactions for 10 aerosol subtypes. The aerosol activation scheme was
also implemented in STRACO condensation-convection scheme. The nucleation is dependent on aerosol properties and the ice phase processes are reformulated in terms of classical nucleation theory. <br>
**See also:** <br>
  - Enviro-HIRLAM short description <a href="/media/model_Enviro-HIRLAM_short.pdf" target="_blank" rel="noopener"><i class="fas fa-file-pdf"></i></a>
  - https://www2.helsinki.fi/en/researchgroups/multi-scale-modelling/enviro-hirlam
  - Introduction lecture on Enviro-HIRLAM and model application <a href="/media/MEGAPOLIS-2021_Enviro-HIRLAM-model_intro_vd2.pdf" target="_blank" rel="noopener"><i class="fas fa-file-pdf"></i></a>
  - Introduction into SSRPs with the Enviro-HIRLAM model ([Part 1](/media/MEGAPOLIS_Intro_Enviro-HIRLAM-SSRPs_part1_vf.pdf))

---

- **EC-Earth** - Resp. [Risto Makkonen](/authors/makkonen/), [Putian Zhou](/authors/putian/) <br>
EC-Earth (see [Hazeleger et al., 2010](https://doi.org/10.1175/2010BAMS2877.1/)) is developed jointly by 28 European research institutes. The Coupled Model Intercomparison Project 5 (CMIP5) was the first CMIP for EC-Earth. EC-Earth comprises of atmosphere model IFS, ocean model NEMO
and vegetation model LPJ-GUESS, coupled with OASIS coupler. Aerosols and chemistry are included through the global chemistry-transport model TM5. The Integrated Forecasting Model (IFS) is the atmospheric model developed at
European Centre for Medium-Range Weather Forecasts. The IFS is coupled to the ocean model NEMO, which is run with 1º horizontal resolution and 42 vertical levels. The ice model LIM is coupled directly to the ocean model. EC-Earth
describes aerosols using a 7-mode size distribution ([Vignati et al., 2004](https://doi.org/10.1029/2003JD004485/)), with 4 soluble and 3 insoluble modes. TM5 includes most abundant aerosol species: sulfate, black carbon, organic carbon, sea salt and mineral dust. TM5 uses a grid of 3ºx2º for aerosols and chemistry. <br>
**See also:** <br>
  - EC-Earth short description <a href="/media/model_EC-Earth_short.pdf" target="_blank" rel="noopener"><i class="fas fa-file-pdf"></i></a>
